// Generated by CoffeeScript 1.12.1
(function() {
  var Infector;

  Infector = (function() {
    function Infector() {}

    Infector.prototype.aliasMethodChain = function(klass, method, feature) {
      var withFeature, withoutFeature;
      withoutFeature = klass.prototype[method];
      withFeature = klass.prototype[method + "With" + feature];
      if (withFeature && withoutFeature) {
        klass.prototype[method + "Without" + feature] = withoutFeature;
        return klass.prototype[method] = withFeature;
      }
    };

    return Infector;

  })();

  module.exports = Infector;

}).call(this);
